'use client'
import './styles/globals.css'

// import { Inter } from 'next/font/google'

import { lightTheme } from "@/themes"
import { CssBaseline, ThemeProvider } from "@mui/material"

// const inter = Inter({ subsets: ['latin'] })

/* export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

interface Props {
  children: React.ReactNode
}

export default function RootLayout({ children, }: Props) {
  return (
    <html lang="en">
      <ThemeProvider theme={ lightTheme }>
        <CssBaseline />
        <body> { children } </body>
      </ThemeProvider>
    </html>
  )
}
